### ISSUE TITLE
NPM Package does not include TS types.

### ISSUE THREAD

**Issue by Viriatto** [kkeeth/npm-stats-api#226]
## Description and reproduction procedure
Package does not include TS types.

## Location

- [ ] Logic
- [X] Environment
- [ ] Others

## How it was discovered
When attempting to import the package, VSCode correctly indicates that it couldn't find any types for it. I've noticed that the repository does have types so it's probably just a matter of uploading them to NPM.

![image](https://github.com/kkeeth/npm-stats-api/assets/70980410/d8e60cfe-15c9-4759-9116-2d878c41607a)

**Comment by kkeeth** [comment]
@Viriatto 
Hi! 

Sorry for the late reply .... Thank you for your suggestion :)

I have updated the software, so could you please install the new version v2.1.0 and check if it works as expected?
Thank you.

**Comment by Viriatto** [comment]
I can confirm that types are now being successfully imported, thank you!
