### ISSUE TITLE
18 month limit

### ISSUE THREAD

**Issue by JeffinSiby** [kkeeth/npm-stats-api#29]
The npmjs api is limited to at most 18 months of data. It may be useful to mention this in the README.md for users who wish to request data exceeding this limit.

See: https://github.com/npm/registry/blob/master/docs/download-counts.md#limits

**Comment by kkeeth** [comment]
@JeffinSiby Thanks for the comment! I'll add it :)

**Comment by kkeeth** [comment]
I've added it and will close it 🙇 
ab66cb219f10001c0d14fde33742e04e574b1a7a
